name: Checkmarx Scan (CxOne)

on:
  push:
    branches: [ main ]
  pull_request:
  workflow_dispatch:

jobs:
  scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Run Checkmarx AST Scan
        uses: Checkmarx/ast-github-action@main
        with:
          base_uri: https://sng.ast.checkmarx.net
          cx_client_id: ${{ secrets.CX_CLIENT_ID }}
          cx_client_secret: ${{ secrets.CX_CLIENT_SECRET }}
          project_name: ${{ github.repository }}
